### ISSUE TITLE
Add mimetype for PDFs that make them open in e.g. firefox?

### ISSUE THREAD

**Issue by ermo** [getsolus/xfce4-desktop-branding#9]
On my XFCE install, clicking a PDF file did nothing until I associated it with firefox.

To me, this seems the most obvious solution, given xfce has no native PDF viewer.

**Comment by EbonJaeger** [comment]
I wonder if it would be better or not to use a dedicated PDF viewer applications. What options do we have? Or is Firefox good enough?

**Comment by ZachBacon** [comment]
> I wonder if it would be better or not to use a dedicated PDF viewer applications. What options do we have? Or is Firefox good enough?

Pretty the only real ones at least gtk would be the gnome ones like evince.

**Comment by ermo** [comment]
> I wonder if it would be better or not to use a dedicated PDF viewer applications. What options do we have? Or is Firefox good enough?

IME, for viewing, FF is quite user friendly.

An alternative could be [xreader](https://github.com/linuxmint/xreader), which might also be useful to Budgie 10...?

Assuming we're serious about deprecating MATE, there's an argument to be made that we might be better off _replacing_ the MATE apps with the [Xapp](https://linuxmint-developer-guide.readthedocs.io/en/latest/xapps.html) ones, then using those to pad out Xfce and Budgie installs...?

Note that we already use slick greeter.

**Comment by EbonJaeger** [comment]
xreader wouldn't be bad; I got a package locally of it working.

**Comment by ermo** [comment]
(EDIT: spoke too soon)

**Comment by EbonJaeger** [comment]
*Technically*, this isn't fixed until the branding package in the repository is updated :P
